swagger: '2.0'
info:
  version: '1.0'
  title: air-flux
  description: 'TODO: Add Description'
  contact: {}
host: 'localhost:8080'
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /flightplan:
    get:
      description: 'TODO: Add Description'
      summary: flightplan
      tags:
        - Misc
      operationId: FlightplanGet
      produces:
        - application/json;charset=UTF-8
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/flightplan'
          examples:
            application/json;charset=UTF-8:
              - origin: MUC
                destination: LHR
                departure: '2018-04-13T20:00+02:00'
                arrival: '2018-04-13T20:00+01:00'
                equipment: 'Airbus 321 '
              - origin: TXL
                destination: MUC
                departure: '2018-04-13T20:00+02:00'
                arrival: '2018-04-13T21:00+02:00'
                equipment: Boeing 737
              - origin: HAM
                destination: MUC
                departure: '2018-04-13T20:00+02:00'
                arrival: '2018-04-13T21:00+02:00'
                equipment: Airbus A320
              - origin: LHR
                destination: HAM
                departure: '2018-04-13T18:00+01:00'
                arrival: '2018-04-13T22:30+02:00'
                equipment: Boeing 747-400
              - origin: MUC
                destination: TXL
                departure: '2018-04-13T23:00+02:00'
                arrival: '2018-04-14T00:00+02:00'
                equipment: Boeing 737
              - origin: HAM
                destination: MUC
                departure: '2018-04-13T23:00+02:00'
                arrival: '2018-04-14T00:00+02:00'
                equipment: Boeing 747-400
              - origin: LHR
                destination: TXL
                departure: '2018-04-13T21:00+01:00'
                arrival: '2018-04-14T01:00+02:00'
                equipment: 'Airbus 321 '
              - origin: MUC
                destination: LHR
                departure: '2018-04-14T01:30+02:00'
                arrival: '2018-04-14T01:30+01:00'
                equipment: Boeing 747-400
              - origin: TXL
                destination: MUC
                departure: '2018-04-14T01:00+02:00'
                arrival: '2018-04-14T02:00+02:00'
                equipment: Boeing 737
              - origin: MUC
                destination: TXL
                departure: '2018-04-14T01:00+02:00'
                arrival: '2018-04-14T02:00+02:00'
                equipment: Airbus A320
              - origin: TXL
                destination: MUC
                departure: '2018-04-14T02:00+02:00'
                arrival: '2018-04-14T03:00+02:00'
                equipment: 'Airbus 321 '
              - origin: MUC
                destination: HAM
                departure: '2018-04-14T03:30+02:00'
                arrival: '2018-04-14T04:30+02:00'
                equipment: Boeing 737
              - origin: MUC
                destination: LHR
                departure: '2018-04-14T04:00+02:00'
                arrival: '2018-04-14T04:30+01:00'
                equipment: 'Airbus 321 '
              - origin: TXL
                destination: MUC
                departure: '2018-04-14T04:00+02:00'
                arrival: '2018-04-14T05:00+02:00'
                equipment: Airbus A320
              - origin: LHR
                destination: TXL
                departure: '2018-04-14T02:00+01:00'
                arrival: '2018-04-14T06:00+02:00'
                equipment: Boeing 747-400
              - origin: MUC
                destination: LHR
                departure: '2018-04-14T06:00+02:00'
                arrival: '2018-04-14T06:00+01:00'
                equipment: Airbus A320
              - origin: HAM
                destination: MUC
                departure: '2018-04-14T06:00+02:00'
                arrival: '2018-04-14T07:00+02:00'
                equipment: Boeing 737
              - origin: TXL
                destination: HAM
                departure: '2018-04-14T07:00+02:00'
                arrival: '2018-04-14T07:40+02:00'
                equipment: Boeing 747-400
              - origin: MUC
                destination: TXL
                departure: '2018-04-14T08:00+02:00'
                arrival: '2018-04-14T09:00+02:00'
                equipment: Boeing 737
              - origin: LHR
                destination: MUC
                departure: '2018-04-14T05:30+01:00'
                arrival: '2018-04-14T09:30+02:00'
                equipment: 'Airbus 321 '
          headers:
            Transfer-Encoding:
              type: string
              default: chunked
            Date:
              type: string
              default: 'Thu, 06 Dec 2018 19:35:24 GMT'
  /operationsplan/FL-0001:
    get:
      description: 'TODO: Add Description'
      summary: operation plan
      tags:
        - Misc
      operationId: OperationsplanFL0001Get
      produces:
        - application/json;charset=UTF-8
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/operationplan'
          examples:
            application/json;charset=UTF-8:
              - origin: TXL
                destination: MUC
                departure: '2018-04-13T20:00+02:00'
              - origin: MUC
                destination: TXL
                departure: '2018-04-13T23:00+02:00'
              - origin: TXL
                destination: MUC
                departure: '2018-04-14T01:00+02:00'
              - origin: MUC
                destination: HAM
                departure: '2018-04-14T03:30+02:00'
              - origin: HAM
                destination: MUC
                departure: '2018-04-14T06:00+02:00'
              - origin: MUC
                destination: TXL
                departure: '2018-04-14T08:00+02:00'
          headers:
            Transfer-Encoding:
              type: string
              default: chunked
            Date:
              type: string
              default: 'Thu, 06 Dec 2018 19:35:22 GMT'
  /flightplan/MUC:
    get:
      description: 'TODO: Add Description'
      summary: flight plan for departure location
      tags:
        - Misc
      operationId: FlightplanMUCGet
      produces:
        - application/json;charset=UTF-8
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/flightplanfordeparturelocation'
          examples:
            application/json;charset=UTF-8:
              - origin: MUC
                destination: LHR
                departure: '2018-04-13T20:00+02:00'
                arrival: '2018-04-13T20:00+01:00'
                equipment: 'Airbus 321 '
              - origin: MUC
                destination: TXL
                departure: '2018-04-13T23:00+02:00'
                arrival: '2018-04-14T00:00+02:00'
                equipment: Boeing 737
              - origin: MUC
                destination: LHR
                departure: '2018-04-14T01:30+02:00'
                arrival: '2018-04-14T01:30+01:00'
                equipment: Boeing 747-400
              - origin: MUC
                destination: TXL
                departure: '2018-04-14T01:00+02:00'
                arrival: '2018-04-14T02:00+02:00'
                equipment: Airbus A320
              - origin: MUC
                destination: HAM
                departure: '2018-04-14T03:30+02:00'
                arrival: '2018-04-14T04:30+02:00'
                equipment: Boeing 737
              - origin: MUC
                destination: LHR
                departure: '2018-04-14T04:00+02:00'
                arrival: '2018-04-14T04:30+01:00'
                equipment: 'Airbus 321 '
              - origin: MUC
                destination: LHR
                departure: '2018-04-14T06:00+02:00'
                arrival: '2018-04-14T06:00+01:00'
                equipment: Airbus A320
              - origin: MUC
                destination: TXL
                departure: '2018-04-14T08:00+02:00'
                arrival: '2018-04-14T09:00+02:00'
                equipment: Boeing 737
          headers:
            Transfer-Encoding:
              type: string
              default: chunked
            Date:
              type: string
              default: 'Thu, 06 Dec 2018 19:35:18 GMT'
definitions:
  flightplan:
    title: flightplan
    example:
      origin: MUC
      destination: LHR
      departure: '2018-04-13T20:00+02:00'
      arrival: '2018-04-13T20:00+01:00'
      equipment: 'Airbus 321 '
    type: object
    properties:
      origin:
        example: MUC
        type: string
      destination:
        example: LHR
        type: string
      departure:
        example: '2018-04-13T20:00+02:00'
        type: string
      arrival:
        example: '2018-04-13T20:00+01:00'
        type: string
      equipment:
        example: 'Airbus 321 '
        type: string
    required:
      - origin
      - destination
      - departure
      - arrival
      - equipment
  operationplan:
    title: operationplan
    example:
      origin: TXL
      destination: MUC
      departure: '2018-04-13T20:00+02:00'
    type: object
    properties:
      origin:
        example: TXL
        type: string
      destination:
        example: MUC
        type: string
      departure:
        example: '2018-04-13T20:00+02:00'
        type: string
    required:
      - origin
      - destination
      - departure
  flightplanfordeparturelocation:
    title: flightplanfordeparturelocation
    example:
      origin: MUC
      destination: LHR
      departure: '2018-04-13T20:00+02:00'
      arrival: '2018-04-13T20:00+01:00'
      equipment: 'Airbus 321 '
    type: object
    properties:
      origin:
        example: MUC
        type: string
      destination:
        example: LHR
        type: string
      departure:
        example: '2018-04-13T20:00+02:00'
        type: string
      arrival:
        example: '2018-04-13T20:00+01:00'
        type: string
      equipment:
        example: 'Airbus 321 '
        type: string
    required:
      - origin
      - destination
      - departure
      - arrival
      - equipment
tags:
  - name: Misc
    description: ''
